export const SERVICES = [
    {name:'Sistemas de detección de incendios', description:'Ingeniería, instalación y mantenimiento', icon:'AlarmIcon'},
    {name:'Sistemas de supresión de incendios', description:'Ingeniería, instalación y mantenimiento', icon:'FireIcon'},
    {name:'Instalaciones eléctricas', description:'Media y baja tensión, industriales, comerciales y residenciales', icon:'LightningIcon'},
    {name:'Ingeniería', description:'Sistemas de detección y prevención de incendios.', icon:'EngineeringIcon'},
]

export const PROJECTS = [
    {name:'Teleperformance One Tower', description:'Se instaló un sistema de detección de incendios y un sistema de supresión de incendios mediante hidrantes en 10 niveles de la torre.',ubication:'Ciudad de México', app:'Detección e hidrantes', images:["https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRjiLFkY6xq5awao4NLFPArQv8uhh2AR2I_tQ&s","imagen2"]},
    {name:'Ethan Allen', description:'Se instaló un sistema de rociadores, con una bomba de 2,500 gpm en los pisos 1 y 2, así como un sistema de detección térmica por cable SafeFire, conectado a un panel Notifier, cumpliendo con las normas NFPA, con supervisión y aprobación de la compañía de seguros internacional.',ubication:'Silao, Guanajuato', app:'Sistema hidráulico', images:["https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRjiLFkY6xq5awao4NLFPArQv8uhh2AR2I_tQ&s","imagen2"]},
    {name:'Compuestos avanzados', description:'Se sustituyó una bomba diésel residencial con certificación UL/FM, cumpliendo con los requisitos de la NFPA 20, junto con el conjunto del cabezal y la conexión al sistema existente.',ubication:'Aguascalientes,Ags', app:'Equipo de bombeo', images:["https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRjiLFkY6xq5awao4NLFPArQv8uhh2AR2I_tQ&s","imagen2"]},
    {name:'Bulkmatic de México', description:'Este sistema fue desarrollado desde cero con base en los estándares de la NFPA, y su instalación consiste en una unidad de bombeo de 1500 GPM, que alimenta un sistema de rociadores en el área de transferencia y hidrantes de monitoreo.También se instaló un sistema de alarma en el área de transferencia, rociadores en la sala de bombas y detección puntual en el área de oficinas.',ubication:'San Luis Potosí, S.L.P', app:'Sistema hidráulico', images:["https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRjiLFkY6xq5awao4NLFPArQv8uhh2AR2I_tQ&s","imagen2"]},
] 